# Generated by Django 3.2.3 on 2021-05-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Destinos',
                'db_table': 'Destino',
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_espaco', models.BigIntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('auxiliar', models.IntegerField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Espaços',
                'db_table': 'Espaco',
                'ordering': ('nome', 'beacon_espaco'),
            },
        ),
        migrations.CreateModel(
            name='LocalApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Local',
                'db_table': 'TipoLocal',
            },
        ),
        migrations.CreateModel(
            name='Percurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField()),
                ('instrucao', models.TextField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percursos', to='web.destino')),
                ('espaco_fim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espaco_fim', to='web.espaco')),
                ('espaco_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espaco_inicio', to='web.espaco')),
            ],
            options={
                'verbose_name_plural': 'Percursos',
                'db_table': 'Percurso',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_local', models.BigIntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('auxiliar', models.CharField(choices=[(0, 'O'), (1, 'A')], max_length=1)),
                ('tipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipolocal')),
            ],
            options={
                'verbose_name_plural': 'Local',
                'db_table': 'Local',
                'ordering': ('nome', 'beacon_local'),
            },
        ),
        migrations.AddField(
            model_name='espaco',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacos', to='web.local'),
        ),
        migrations.AddField(
            model_name='destino',
            name='espaco_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='web.espaco'),
        ),
        migrations.AddField(
            model_name='destino',
            name='espaco_inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='web.espaco'),
        ),
    ]
